import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {validateGearBundle} from './gear-model.js';
import {readValidatedImage} from './image-validation.mjs';
const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url),'utf8'));
const gear=read('./data/gear.seed.json');
assert.ok(validateGearBundle(gear).valid);
assert.equal(gear.schemaVersion,4);
assert.equal(gear.dataVersion,'2026-09-08-my-gear-v4-dagger-length-1');
assert.equal(gear.items.length,65);
const id='dagger-axis-10-5';
const expected={"id":"dagger-axis-10-5","category":"accessories","type":"Kayaks","name":"Dagger Axis 10.5","manufacturer":{"name":"Dagger"},"model":"Axis 10.5","specifications":[{"label":"Length","value":"10' 6\""},{"label":"Height","value":"15.25\""},{"label":"Width","value":"28.5\""},{"label":"Weight","value":"50 lb"},{"label":"Cockpit opening","value":"52.5\"x23.5\" (6.0 deck)"}],"links":[{"label":"Dagger","url":"https://www.confluenceoutdoor.com/products/dagger-axis-105-crossover-kayak-9030515209?_pos=1&_psq=axis&_psid=22657cf47&_ss=e"}]};
assert.deepEqual(gear.items.filter(x=>x.id===id),[expected]);
const sources=read('./media-sources.json');
const owners=read('./media-owners.json');
const local=read('./local-media.json');
assert.equal(sources.items.filter(x=>x.id===id).length,1);
assert.equal(sources.items.find(x=>x.id===id).sourcePage,'https://www.confluenceoutdoor.com/products/dagger-axis-105-crossover-kayak-9030515209?_pos=1&_psq=axis&_psid=22657cf47&_ss=e');
assert.deepEqual(owners.items.find(x=>x.mediaId===id).owners,[{gearItemId:id}]);
const entry=local.gear.find(x=>x.mediaId===id);
assert.equal(entry.source,'./assets/gear-source/dagger-axis-10-5.png');
assert.deepEqual(entry.owners,[{gearItemId:id}]);
assert.equal(entry.destination,'https://www.confluenceoutdoor.com/products/dagger-axis-105-crossover-kayak-9030515209?_pos=1&_psq=axis&_psid=22657cf47&_ss=e');
assert.equal(local.gear.filter(x=>x.mediaId===id).length,1);
assert.equal(fs.existsSync(new URL('./gear-content/'+id+'.md',import.meta.url)),false);
const bytes=await readValidatedImage(fileURLToPath(new URL(entry.source,import.meta.url)));
const blob=crypto.createHash('sha1').update('blob '+bytes.length+'\0').update(bytes).digest('hex');
assert.equal(blob,'17ad66ac19cc0a71f3ca4c3fd4ea6ec5e881ac51');
assert.equal(bytes.length,393226);
if(process.argv.includes('--dist')) {
 const built=read('./dist/data/gear.seed.json');
 assert.deepEqual(built.items.find(x=>x.id===id),expected);
 const media=read('./dist/gear-media.json').find(x=>x.id===id);
 assert.ok(media);
 assert.equal(media.asset,'./assets/gear/dagger-axis-10-5.png');
 assert.deepEqual(media.owners,[{gearItemId:id}]);
 assert.equal(media.localSource,true);
 assert.equal(media.sourcePath,'pwa/assets/gear-source/dagger-axis-10-5.png');
 assert.deepEqual(fs.readFileSync(new URL('./dist/assets/gear/dagger-axis-10-5.png',import.meta.url)),bytes);
}
console.log('Dagger Axis source identity, exact authored facts, ownership and media validation passed.');
