import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { readValidatedImage } from './image-validation.mjs';
import { renderMarkdown } from './markdown-render.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const source = await fs.readFile(path.join(here,'gear-app.js'),'utf8');
assert.match(source,/name="gearPictureAction" value="keep" checked/);
assert.match(source,/name="gearPictureAction" value="replace"/);
assert.match(source,/context\.hasPicture && pictureAction !== 'replace'/);
assert.match(source,/const mediaId = context\.currentMediaId \|\| current\?\.id \|\| id;/);
assert.match(source,/currentMedia\?\.sourcePath \|\| currentMedia\?\.imageSource/);
assert.match(source,/sourceFilename:filename, uploadPath/);
assert.match(source,/Current picture:[\s\S]*Media ID:/);
assert.doesNotMatch(source,/filename !== context\.currentFilename/);

// Exercise the actual pure change classifier without browser-only module initialization.
const begin = source.indexOf('function pictureChange(');
const end = source.indexOf('function notesChange(', begin);
assert.ok(begin >= 0 && end > begin);
const pictureChange = (await import('data:text/javascript,' + encodeURIComponent(source.slice(begin,end) + '\nexport { pictureChange };'))).pictureChange;
const currentMedia = {id:'thkfish-cylinder-weights',asset:'./assets/gear/thkfish-cylinder-weights.jpg',imageSource:'https://example.com/original.jpg'};
const context = {hasPicture:true,currentMedia,currentMediaId:currentMedia.id,currentFilename:''};
assert.equal(pictureChange(context,true,'cylinder-weights.png','cylinder-weights','keep').action,'keep');
const replacement = pictureChange(context,true,'cylinder-weights.png','cylinder-weights','replace');
assert.equal(replacement.action,'replace');
assert.equal(replacement.mediaId,'thkfish-cylinder-weights');
assert.equal(replacement.uploadPath,'pwa/assets/gear-source/cylinder-weights.png');
assert.equal(replacement.currentSource,'https://example.com/original.jpg');
assert.equal(pictureChange({...context,currentFilename:'cylinder-weights.png'},true,'cylinder-weights.png','cylinder-weights','replace').action,'replace','Same filename must still replace.');
assert.equal(pictureChange(context,false,'','cylinder-weights','keep').action,'remove');
assert.equal(pictureChange({hasPicture:false},true,'new-kayak.jpg','new-kayak','add').action,'add');

const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl5C2kAAAAASUVORK5CYII=','base64');
const fixture = await fs.mkdtemp(path.join(os.tmpdir(),'fishing-notes-media-'));
const pwa = path.join(fixture,'pwa');
const write = async (relative,contents) => { const filename=path.join(pwa,relative); await fs.mkdir(path.dirname(filename),{recursive:true}); await fs.writeFile(filename,contents); };
const build = () => execFileSync(process.execPath,[path.join(pwa,'apply-authored-notes.mjs')],{cwd:fixture,encoding:'utf8',stdio:'pipe'});
const failed = message => { assert.throws(build, error => String(error.stderr || error.message).includes(message),message); };
try {
  await fs.mkdir(pwa,{recursive:true});
  for (const filename of ['apply-authored-notes.mjs','image-validation.mjs']) await fs.copyFile(path.join(here,filename),path.join(pwa,filename));
  await write('data/gear.seed.json',JSON.stringify({items:[{id:'test-kayak'}]}));
  await write('data/catches.seed.json',JSON.stringify({catches:[]}));
  await write('data/kb.seed.json',JSON.stringify({entities:[]}));
  await write('gear-content/test-kayak-bow.png',png);
  await write('gear-content/test-kayak.md','![Bow hatch](test-kayak-bow.png)\n');
  build();
  assert.deepEqual(await fs.readFile(path.join(pwa,'dist/gear-content/test-kayak-bow.png')),png);
  const assets=JSON.parse(await fs.readFile(path.join(pwa,'dist/gear-notes-assets.json'),'utf8'));
  assert.ok(assets.includes('./gear-content/test-kayak-bow.png'));
  assert.ok(assets.includes('./gear-content/test-kayak.md'));
  assert.match(renderMarkdown('![Bow hatch](test-kayak-bow.png)',{contentPath:'./gear-content/test-kayak.md'}),/src="\.\/gear-content\/test-kayak-bow\.png"/);
  await write('assets/gear-notes/test-kayak-old.png',png);
  await write('gear-content/test-kayak.md','![Old](../assets/gear-notes/test-kayak-old.png)\n');
  build();
  assert.ok(JSON.parse(await fs.readFile(path.join(pwa,'dist/gear-notes-assets.json'),'utf8')).includes('./assets/gear-notes/test-kayak-old.png'));
  await write('gear-content/test-kayak.md','![Wrong](other-kayak-bow.png)\n');
  failed('outside its approved Notes image locations');
  await write('gear-content/test-kayak.md','![Wrong](../assets/gear-source/test-kayak-bow.png)\n');
  failed('outside its approved Notes image locations');
  await write('gear-content/test-kayak.md','![Missing](test-kayak-missing.png)\n');
  failed('Missing required Gear Notes asset');
  await write('gear-content/test-kayak.md','![Bad](test-kayak-bow.png)\n');
  await write('gear-content/test-kayak-bow.png',Buffer.from('not an image'));
  failed('Unsupported or structurally invalid image');
  await write('gear-content/test-kayak-bow.png',png);
  await write('gear-content/test-kayak-bow.jpg',png);
  await write('gear-content/test-kayak.md','![Bad](test-kayak-bow.jpg)\n');
  failed('Image extension does not match content');
  await write('gear-content/test-kayak.md','![Too large](test-kayak-bow.png)\n');
  await write('gear-content/test-kayak-bow.png',Buffer.alloc(10*1024*1024+1));
  failed('Invalid image size');
  await write('gear-content/test-kayak-bow.png',png);
  await readValidatedImage(path.join(pwa,'gear-content/test-kayak-bow.png'));
  console.log('Notes sibling/legacy image validation, byte preservation, offline manifest, and explicit picture replacement tests passed.');
} finally {
  await fs.rm(fixture,{recursive:true,force:true});
}
