import assert from 'node:assert/strict';
import fs from 'node:fs';
import { validateKbBundle } from './kb-model.js';
import { materializeKbEntity,validateKbMediaBundle } from './kb-picture-model.js';
import { newKbIdentity,newKbContentPath,prepareKbChange,validateKbChangePackage,validateKbMarkdown,authoredTargets } from './kb-authoring-model.js';
const read = path => JSON.parse(fs.readFileSync(new URL(path,import.meta.url),'utf8'));
const kb=read('./data/kb.seed.json'),gear=read('./data/gear.seed.json'),catches=read('./data/catches.seed.json');
const original=kb.entities.find(row=>row.id==='technique-ned-rig');
const markdown=fs.readFileSync(new URL(original.content,import.meta.url),'utf8');
const input={bundle:kb,gearBundle:gear,catchBundle:catches,original,originalMarkdown:markdown,
 entity:{...original,name:'Ned Rig Updated'},markdown,picturePlan:{action:original.picture?'keep':'none'}};
const checked=()=>prepareKbChange(input);
assert.equal(checked().valid,true,checked().errors.join('; '));
assert.equal(validateKbChangePackage(checked().package,kb,gear,catches,markdown).valid,true);
assert.equal(checked().package.entity.id,original.id);
assert.equal(checked().package.entity.content,original.content);
assert.equal(checked().package.content.action,'keep');
assert.equal(checked().package.picture.action,original.picture?'keep':'none');
assert.equal(prepareKbChange({...input,entity:{...input.entity,type:'technique'}}).valid,true,'Reclassification must preserve existing IDs and paths.');
assert.equal(prepareKbChange({...input,entity:{...input.entity,id:'technique-renamed'}}).valid,false);
assert.equal(prepareKbChange({...input,entity:{...input.entity,content:'./kb-content/techniques/renamed.md'}}).valid,false);
const species=kb.entities.find(row=>row.id==='species-perch');
assert.equal(prepareKbChange({...input,original:species,entity:{...species,type:'equipment'},originalMarkdown:'Original',markdown:'Original',picturePlan:{action:'keep'}}).valid,false,'Catch references must prevent invalid reclassification.');
const clone=structuredClone(kb);clone.entities.find(row=>row.id===original.id).type='location';
assert.equal(validateKbBundle(clone).valid,true,'Historical prefixes are not type constraints.');
assert.equal(newKbIdentity('equipment','Texas Rig',kb),'equipment-texas-rig');
const newId=newKbIdentity('equipment','Texas Rig',kb);
const newEntity={id:newId,type:'equipment',name:'Texas Rig',description:null,picture:null,content:newKbContentPath('equipment',newId)};
const add=prepareKbChange({bundle:kb,gearBundle:gear,catchBundle:catches,entity:newEntity,markdown:'# Texas Rig\n\nSee [Ned](kb://technique-ned-rig).',picturePlan:{action:'none'}});
assert.equal(add.valid,true,add.errors.join('; '));
assert.equal(validateKbChangePackage(add.package,kb,gear,catches).valid,true);
assert.equal(add.package.content.path,'pwa/kb-content/equipment/equipment-texas-rig.md');
assert.equal(prepareKbChange({...input,entity:{...input.entity,description:'x'.repeat(81)}}).valid,false);
assert.equal(prepareKbChange({...input,markdown:'See [missing](kb://no-such-id).'}).valid,false);
assert.equal(prepareKbChange({...input,markdown:'[bad](javascript:alert)'}).valid,false);
assert.equal(prepareKbChange({...input,markdown:'[bad](#/kb/entity/species-perch)'}).valid,false);
assert.equal(prepareKbChange({...input,markdown:'[bad](../../../../escape.md)'}).valid,false);
assert.equal(prepareKbChange({...input,markdown:'![bad](../../../../escape.png)'}).valid,false);
assert.deepEqual(authoredTargets('```md\n[example](kb://missing)\n```\n[real](kb://species-perch)'),['kb://species-perch']);
assert.deepEqual(validateKbMarkdown('![Image](../../assets/kb/equipment/ned-rig.png)',original,kb,gear),[]);
const stale=structuredClone(kb);stale.dataVersion='changed';
assert.equal(validateKbChangePackage(checked().package,stale,gear,catches,markdown).valid,false);
assert.equal(validateKbChangePackage(checked().package,kb,gear,catches,markdown+' changed').valid,false);
const tampered=structuredClone(checked().package);tampered.entity.name='Unvalidated change';
assert.equal(validateKbChangePackage(tampered,kb,gear,catches,markdown).valid,false);
const pictured=kb.entities.find(row=>row.id==='species-perch');
const picturedMarkdown=fs.readFileSync(new URL(pictured.content,import.meta.url),'utf8');
const picturedInput={...input,original:pictured,entity:{...pictured},originalMarkdown:picturedMarkdown,markdown:picturedMarkdown};
const uploadPlan={action:'replace',filename:`${pictured.id}-hero.jpg`,alt:'Ned rig illustration',caption:'Ned rig',sourceUrl:'https://example.com/source'};
const upload=prepareKbChange({...picturedInput,picturePlan:uploadPlan});
assert.equal(upload.valid,true,upload.errors.join('; '));
assert.equal(upload.package.picture.uploadPath,`pwa/assets/kb/entries/${pictured.id}-hero.jpg`);
assert.deepEqual(upload.package.picture.current,pictured.picture);
assert.equal(validateKbChangePackage(upload.package,kb,gear,catches,picturedMarkdown).valid,true);
assert.equal(prepareKbChange({...picturedInput,picturePlan:{...uploadPlan,filename:'../escape.jpg'}}).valid,false);
const reuseMedia=[{id:'owned-media',asset:'./assets/gear/owned.jpg',alt:'Owned lure',owners:[{gearItemId:'berkley-stunna'}]}];
const reuse=prepareKbChange({...picturedInput,picturePlan:{action:'reuse',gearMediaId:'owned-media',availableMedia:reuseMedia,alt:'Owned lure',gearItemId:'berkley-stunna'}});
assert.equal(reuse.valid,true,reuse.errors.join('; '));
assert.equal(reuse.package.entity.picture.gearItemId,'berkley-stunna');
assert.equal(validateKbChangePackage(reuse.package,kb,gear,catches,picturedMarkdown,reuseMedia).valid,true);
assert.equal(validateKbChangePackage(reuse.package,kb,gear,catches,picturedMarkdown,[]).valid,false);
const removal=prepareKbChange({...picturedInput,picturePlan:{action:'remove'}});
assert.equal(removal.valid,true);
assert.equal(removal.package.entity.picture,null);
assert.deepEqual(removal.package.picture.current,pictured.picture);
assert.equal(validateKbChangePackage(removal.package,kb,gear,catches,picturedMarkdown).valid,true);
const badOverlay={version:1,kb:[{entityId:'species-perch',source:'./assets/kb/species/perch.png',alt:'Perch'},{entityId:'species-perch',source:'./assets/kb/species/perch.png',alt:'Perch'}]};
assert.equal(validateKbMediaBundle(badOverlay,kb,gear).valid,false);
assert.throws(()=>materializeKbEntity(pictured,badOverlay),/Duplicate KB media/);
const unknownOwner={version:1,kb:[{entityId:'species-perch',source:'./assets/kb/species/perch.png',alt:'Perch',gearItemId:'missing-owned-id'}]};
assert.equal(validateKbMediaBundle(unknownOwner,kb,gear).valid,false);
console.log('KB Add/Edit identity, content, reclassification, picture, stale-package and cross-domain validation tests passed.');
