import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {prepareKbChange} from './kb-authoring-model.js';
import {promoteKbChange} from './promote-kb-change.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));
const read=async name=>JSON.parse(await fs.readFile(path.join(here,name),'utf8'));
const [kb,gear,catches,local]=await Promise.all(['data/kb.seed.json','data/gear.seed.json','data/catches.seed.json','local-media.json'].map(read));
const sourceMedia=await read('media-sources.json');
const sourceOwners=await read('media-owners.json');
const owners=new Map(sourceOwners.items.map(row=>[row.mediaId,row.owners]));
const availableMedia=sourceMedia.items.filter(row=>owners.has(row.id)).map(row=>({id:row.id,asset:`./assets/gear/${row.id}.png`,alt:row.alt,owners:owners.get(row.id)}));
const promote=(pkg,options={})=>promoteKbChange(pkg,{root,availableMedia,...options});
const root=await fs.mkdtemp(path.join(os.tmpdir(),'fishing-kb-promotion-'));
const write=async (name,bytes)=>{const target=path.join(root,'pwa',name);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,bytes);};
const readFixture=async name=>JSON.parse(await fs.readFile(path.join(root,'pwa',name),'utf8'));
const fixture=async()=>{
  for(const [name,data] of [['data/kb.seed.json',kb],['data/gear.seed.json',gear],['data/catches.seed.json',catches],['local-media.json',local]])await write(name,JSON.stringify(data));
  const entity=kb.entities.find(row=>row.id==='species-perch');
  const markdown=await fs.readFile(path.join(here,entity.content),'utf8');
  await write(entity.content,markdown);
  return {entity,markdown};
};
try {
  const {entity,markdown}=await fixture();
  const base={bundle:kb,gearBundle:gear,catchBundle:catches,original:entity,originalMarkdown:markdown,entity:{...entity,name:'Yellow Perch Updated'},markdown};
  const prepared=prepareKbChange({...base,picturePlan:{action:'keep'}}).package;
  const before=await fs.readFile(path.join(root,'pwa/data/kb.seed.json'));
  await promote(prepared);
  assert.deepEqual(await fs.readFile(path.join(root,'pwa/data/kb.seed.json')),before,'Dry run must not write source.');
  await promote(prepared,{apply:true,dataVersion:'test-kb-edit-1'});
  let next=await readFixture('data/kb.seed.json');
  assert.equal(next.dataVersion,'test-kb-edit-1');
  assert.equal(next.entities.length,kb.entities.length);
  assert.equal(next.entities.find(row=>row.id===entity.id).content,entity.content);
  assert.equal(next.entities.find(row=>row.id===entity.id).name,'Yellow Perch Updated');
  assert.equal(await fs.readFile(path.join(root,'pwa',entity.content),'utf8'),markdown);
  await assert.rejects(promote(prepared,{apply:true}),/data version has changed|existing entity has changed/);

  await fixture();
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl5C2kAAAAASUVORK5CYII=','base64');
  const upload=prepareKbChange({...base,picturePlan:{action:'replace',filename:`${entity.id}-hero.png`,alt:'Yellow perch'}}).package;
  await assert.rejects(promote(upload,{apply:true}),/Missing required image asset/);
  assert.deepEqual(await fs.readFile(path.join(root,'pwa/data/kb.seed.json')),before,'Missing upload must not change source.');
  await write(`assets/kb/entries/${entity.id}-hero.png`,png);
  await promote(upload,{apply:true,dataVersion:'test-kb-image-1'});
  next=await readFixture('data/kb.seed.json');
  assert.equal(next.entities.find(row=>row.id===entity.id).picture.src,`./assets/kb/entries/${entity.id}-hero.png`);
  assert.deepEqual((await readFixture('local-media.json')).kb.find(row=>row.entityId===entity.id).source,`./assets/kb/entries/${entity.id}-hero.png`);
  assert.deepEqual(await fs.readFile(path.join(root,`pwa/assets/kb/entries/${entity.id}-hero.png`)),png);
  assert.equal((await readFixture('kb-media-history.json')).entries.length,1,'Replacement must retain original picture provenance.');
  await fixture();
  const removal=prepareKbChange({...base,picturePlan:{action:'remove'}}).package;
  await promote(removal,{apply:true,dataVersion:'test-kb-remove-1'});
  assert.equal((await readFixture('local-media.json')).kb.some(row=>row.entityId===entity.id),false);
  assert.equal((await readFixture('data/kb.seed.json')).entities.find(row=>row.id===entity.id).picture,null);
  assert.equal((await readFixture('kb-media-history.json')).entries.length,2,'Removal must retain prior media history.');
  assert.deepEqual(await fs.readFile(path.join(root,`pwa/assets/kb/entries/${entity.id}-hero.png`)),png,'Removing an association must never delete image bytes.');

  await fixture();
  const id='equipment-test-promotion';
  const added=prepareKbChange({bundle:kb,gearBundle:gear,catchBundle:catches,entity:{id,type:'equipment',name:'Test Promotion',description:null,picture:null,content:`./kb-content/equipment/${id}.md`},markdown:'# Test Promotion\n\nA complete article.',picturePlan:{action:'none'}}).package;
  await promote(added,{apply:true,dataVersion:'test-kb-add-1'});
  next=await readFixture('data/kb.seed.json');
  assert.equal(next.entities.length,kb.entities.length+1);
  assert.equal(await fs.readFile(path.join(root,`pwa/kb-content/equipment/${id}.md`),'utf8'),added.content.markdown);
  await assert.rejects(promote(added,{apply:true}),/already exists|data version has changed/);
  console.log('KB repository promotion dry-run, stale checks, add/edit, image validation, and non-destructive removal tests passed.');
} finally {await fs.rm(root,{recursive:true,force:true});}
